export const postConstants = {
  GET_REQUEST: 'POSTS_GET_REQUEST',
  GET_SUCCESS: 'POSTS_GET_SUCCESS',
  GET_FAILURE: 'POSTS_GET_FAILURE',

  CREATE_REQUEST: 'CREATE_POST_REQUEST',
  CREATE_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_FAILURE: 'CREATE_POST_FAILURE',

  DELET_REQUEST: 'DELETE_POST_REQUEST',
  DELET_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_FAILURE: 'DELETE_POST_FAILURE',
};
