export const userConstants = {
  SIGN_UP_REQUEST: 'USERS_SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'USERS_SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'USERS_SIGN_UP_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
};
